apiVersion: apps/v1
kind: Deployment
metadata:
  name: martini
  labels:
    app: martini
spec:
  # shiny apps are stateful, and do not work very well with more than 1 replica
  # see discussion https://github.com/rstudio/shiny/issues/2455
  replicas: 1
  selector:
    matchLabels:
      app: martini
  template:
    metadata:
      labels:
        app: martini
    spec:
      containers:
      - name: martini
        image: europe-west1-docker.pkg.dev/niva-cd/images/martini:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
          - containerPort: 3838
        livenessProbe:
          httpGet:
            path: /
            port: 3838
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3838
          periodSeconds: 10
---
# Service exposing the timescale DB
apiVersion: v1
kind: Service
metadata:
  name: martini
spec:
  ports:
  - port: 3838
    protocol: TCP
  selector:
    app: martini
